### ISSUE TITLE
Allow sheets in atlante to have multiple styles associated with them.

### ISSUE THREAD

**Issue by gdey** [go-spatial/atlante#115]
We will make two major changes to the way the config work.
One introduces a new top-level section called styles

```toml
[[styles]]
style_name = "url://to_style"

```

In sheats, the "style" configuration will be deprecated and a new "styles" entry will be used instead.

```toml
[[sheets]]
   styles = ["style_name","style_name",...]
```

Where the first style_name is considered the default.

If both `styles` and `style` exist, then `styles` will be used. If only `style` exists, it will be treated as a `styles` entry with only one entry in it. It will, also, receive a key name of `style`.
